export const pitchingStatConfig = [
	{
		key: 'exit_velocity',
		label: 'Exit Velocity Against',
		category: 'profile',
		description: 'The average speed (in mph) of all batted balls allowed off the bat.'
	},
	{
		key: 'max_ev',
		label: 'Max Exit Velocity Against',
		category: 'profile',
		description: 'The absolute maximum speed recorded on any single batted ball allowed.'
	},
	{
		key: 'hard_hit_percent',
		label: 'Hard Hit Percentage Against',
		category: 'profile',
		description: 'The percentage of batted balls allowed at 95 mph or faster.'
	},
	{
		key: 'brl',
		label: 'Barrels Allowed',
		category: 'profile',
		description:
			'The raw number of batted balls allowed meeting optimal launch angle and exit velocity thresholds.'
	},
	{
		key: 'brl_percent',
		label: 'Barrel Percentage Against',
		category: 'profile',
		description: 'The percentage of total batted balls allowed that are classified as Barrels.'
	},
	{
		key: 'bat_speed',
		label: 'Bat Speed Against',
		category: 'profile',
		description: 'The average bat speed generated by opposing batters when making contact.'
	},
	{
		key: 'swing_length',
		label: 'Swing Length Against',
		category: 'profile',
		description: 'The average swing path length of opposing hitters facing this pitcher.'
	},
	{
		key: 'squared_up_rate',
		label: 'Squared Up Rate Against',
		category: 'profile',
		description: 'The percentage of possible exit velocity achieved by batters facing this pitcher.'
	},
	{
		key: 'bb_percent',
		label: 'Walk Percentage Against',
		category: 'discipline',
		description:
			'How often the pitcher issues a walk as a percentage of overall plate appearances faced.'
	},
	{
		key: 'k_percent',
		label: 'Strikeout Percentage Against',
		category: 'discipline',
		description:
			'How often the pitcher records a strikeout as a percentage of overall plate appearances faced.'
	},
	{
		key: 'chase_percent',
		label: 'Chase Percentage Against',
		category: 'discipline',
		description:
			'The frequency with which opposing batters swing at pitches thrown outside the strike zone.'
	},
	{
		key: 'whiff_percent',
		label: 'Whiff Percentage Against',
		category: 'discipline',
		description:
			'The rate at which opposing batters swing and miss completely against this pitcher.'
	},
	{
		key: 'xba',
		label: 'Expected BA Against',
		category: 'expected',
		description:
			'Expected Batting Average allowed based on contact quality and launch angle, independent of defense.'
	},
	{
		key: 'xobp',
		label: 'Expected OBP Against',
		category: 'expected',
		description:
			'Expected On-Base Percentage allowed, combining contact quality metrics with walk and strikeout rates.'
	},
	{
		key: 'xslg',
		label: 'Expected SLG Against',
		category: 'expected',
		description:
			'Expected Slugging Percentage allowed, measuring modeled extra-base damage based on launch vectors.'
	},
	{
		key: 'xiso',
		label: 'Expected ISO Against',
		category: 'expected',
		description:
			'Expected Isolated Power allowed (xSLG minus xBA), measuring extra-base power yielded to batters.'
	},
	{
		key: 'xwoba',
		label: 'Expected wOBA Against',
		category: 'expected',
		description:
			'Expected Weighted On-Base Average allowed, assigning proportional run values to all contact outcomes.'
	}
];
